"""Dvarios

Revision ID: 10fd3f720863
Revises: 443cef9e2457
Create Date: 2024-08-05 19:51:10.387909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fd3f720863'
down_revision = '443cef9e2457'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
