"""Drename_level

Revision ID: 2ca9ba157bb5
Revises: 2060f0dde4ae
Create Date: 2024-08-23 17:25:40.102144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca9ba157bb5'
down_revision = '2060f0dde4ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_event_coupon')
    op.drop_table('payments_commission_agent')
    op.drop_table('payments_payments')
    op.add_column('tournaments_tournaments', sa.Column('level', sa.String(), nullable=True))
    op.drop_column('tournaments_tournaments', 'type_tournament')
    op.add_column('users_appusers', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('users_appusers', 'nivel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_appusers', sa.Column('nivel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users_appusers', 'level')
    op.add_column('tournaments_tournaments', sa.Column('type_tournament', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tournaments_tournaments', 'level')
    op.create_table('payments_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commission_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tournaments_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hour', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_pay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payments_payments_pkey')
    )
    op.create_table('payments_commission_agent',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payments_commission_agent_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payments_commission_agent_pkey'),
    sa.UniqueConstraint('appuser_id', name='payments_commission_agent_appuser_id_key'),
    sa.UniqueConstraint('codigo', name='payments_commission_agent_codigo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments_event_coupon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commission_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tournaments_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commission_agent_id'], ['payments_commission_agent.id'], name='payments_event_coupon_commission_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_event_coupon_pkey')
    )
    # ### end Alembic commands ###
