"""Dañadir_quota_reward_en_tournament

Revision ID: 443cef9e2457
Revises: eeda690c50a8
Create Date: 2024-07-27 06:09:20.652043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443cef9e2457'
down_revision = 'eeda690c50a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_tournaments', sa.Column('quota', sa.Integer(), nullable=True))
    op.add_column('tournaments_tournaments', sa.Column('reward', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_tournaments', 'reward')
    op.drop_column('tournaments_tournaments', 'quota')
    # ### end Alembic commands ###
