"""adding_status_payment

Revision ID: a30d4e51f4d1
Revises: 2ca9ba157bb5
Create Date: 2024-09-23 15:21:12.046601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a30d4e51f4d1'
down_revision = '2ca9ba157bb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_commission_agent',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payments_commission_agent_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payments_commission_agent_pkey'),
    sa.UniqueConstraint('appuser_id', name='payments_commission_agent_appuser_id_key'),
    sa.UniqueConstraint('codigo', name='payments_commission_agent_codigo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments_event_coupon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hour', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commission_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tournaments_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commission_agent_id'], ['payments_commission_agent.id'], name='payments_event_coupon_commission_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_event_coupon_pkey')
    )
    op.create_table('payments_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commission_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tournaments_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hour', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pay_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_mercado_pago', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_paid_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_received_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payments_payments_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_payments')
    op.drop_table('payments_event_coupon')
    op.drop_table('payments_commission_agent')
    # ### end Alembic commands ###
