"""Add is_active, type_tournament, stage to Tournaments

Revision ID: eeda690c50a8
Revises: 
Create Date: 2024-07-27 05:34:41.459676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeda690c50a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_table('users_notifications_schedule')
    op.add_column('tournaments_tournaments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tournaments_tournaments', sa.Column('type_tournament', sa.String(), nullable=True))
    op.add_column('tournaments_tournaments', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_tournaments', 'stage')
    op.drop_column('tournaments_tournaments', 'type_tournament')
    op.drop_column('tournaments_tournaments', 'is_active')
    op.create_table('users_notifications_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('football_games_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('send', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_notifications_schedule_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
