version: '3.7'

services:
  backend:
    env_file:
      - ../.env
    build: .
    volumes:
      - ./:/proj
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
